### ISSUE TITLE
Dúvidas nas aulas #007, #008 e #009 - MAC

### ISSUE THREAD

**Issue by lianebez** [CollabCodeTech/forum-do-front-ao-end#102]
Pessoal, estou bem atrasada nas aulas e hoje fiz um "intensivão" de 03 aulas e fiquei com algumas dúvidas.

Aula 007 - Layout da busca
Quando coloco color:inherit no .header-store [type="search"] ele não pega a cor no google Chrome, confere? 

Aula 008 - vídeo "Mundo real dentro do sistema""
quando dou tab para mudar o active dos botões ele funciona no botão "Adiciona no carrinho" mas quando dou mais um tab para ir para o botão "comprar" ele não vai. Alguém sabe o porque?

Aula 009 - SSH
Não consegui fazer nada do que o Bruno falou no vídeo. Hoje estou usando o iTerm e ZSH e ele não me pede login e senha. Preciso mesmo trocar para SSH? Lembrando que estou no MAC.

Esse terminal ainda é um monstro para mim =)

Obrigada

**Comment by Pliavi** [comment]
Opa, olá @lianebez 

Sobre os casos, aí estão o seguinte:

#### Aula 007
Confere, não foi comentado nas aulas, mas chegaram a conversar no Telegram, para fazer com que a busca troque a cor é necessário utilizar o seletor do pseudo-elemento 'placeholder', sendo ele "::placeholder", então tu deve colocar a cor por ele usando o seguinte selector:
```css
 .header-store [type="search"]::placholder {}
```
Obs: Só não tenho certeza se o `inherit` irá funcionar nele, mas confirma aí
Esse seletor é padrão para utilização na seleção do placeholder, então sempre que for editar algo do placeholder utilize-o, passar o color direto no input é só uma alternativa, mas não recomendada.

#### Aula 008
Isso talvez seja um problema com o `tabindex` geralmente ele segue a ordem que as coisas aparecem no html, ele deve estar indo para algum outro elemento antes, precisaria ver seu código pra entender o que está acontecendo.
Mas pra obrigar o tab a seguir a ordem que você quer você pode usar `tabindex=0` e `tabindex=1` em cada botão.

#### Aula 009 
Isso é bem estranho, geralmente ele pede os dados, só se você já tinha feito o esquema com a chave antes.
Mas não é necessário fazê-lo.

Bons estudos!

**Comment by flaviaguterres** [comment]
@lianebez, sobre a questão da aula 007, tive o mesmo problema e o pessoal do grupo no Telegram sugeriu o exemplo abaixo e no meu projeto deu certo:
```
.header-store ::placeholder {
    color: inherit;
}
```

**Comment by lianebez** [comment]
Muito obrigada. Vou dar uma olhada no que vocês falaram

**Comment by Pliavi** [comment]
> @Pliavi Como faço para deixar o código colorido em Markdown?

Usando três crases e o nome da linguagem em seguida, todo código que escrever entre as crases vai ficar colorido, serve pra qualquer linguagem suportada pelo GitHub.

```md
```css
.seu-css{
   color: aqui;
}
\```
```
(Sem essa barra, que só coloquei por markdown não pensar que to abrindo outro bloco de código)

**Comment by flaviaguterres** [comment]
> > @Pliavi Como faço para deixar o código colorido em Markdown?
> 
> Usando três crases e o nome da linguagem em seguida, todo código que escrever entre as crases vai ficar colorido, serve pra qualquer linguagem suportada pelo GitHub.
> 
> ```lisp
> ```css
> .seu-css{
>    color: aqui;
> }
> \```
> ```
> 
> (Sem essa barra, que só coloquei por markdown não pensar que to abrindo outro bloco de código)

Obrigada, @Pliavi! :)

**Comment by lianebez** [comment]
> Opa, olá @lianebez
> 
> Sobre os casos, aí estão o seguinte:
> 
> #### Aula 007
> Confere, não foi comentado nas aulas, mas chegaram a conversar no Telegram, para fazer com que a busca troque a cor é necessário utilizar o seletor do pseudo-elemento 'placeholder', sendo ele "::placeholder", então tu deve colocar a cor por ele usando o seguinte selector:
> 
> ```css
>  .header-store [type="search"]::placholder {}
> ```
> 
> Obs: Só não tenho certeza se o `inherit` irá funcionar nele, mas confirma aí
> Esse seletor é padrão para utilização na seleção do placeholder, então sempre que for editar algo do placeholder utilize-o, passar o color direto no input é só uma alternativa, mas não recomendada.
> 
> #### Aula 008
> Isso talvez seja um problema com o `tabindex` geralmente ele segue a ordem que as coisas aparecem no html, ele deve estar indo para algum outro elemento antes, precisaria ver seu código pra entender o que está acontecendo.
> Mas pra obrigar o tab a seguir a ordem que você quer você pode usar `tabindex=0` e `tabindex=1` em cada botão.
> 
> #### Aula 009
> Isso é bem estranho, geralmente ele pede os dados, só se você já tinha feito o esquema com a chave antes.
> Mas não é necessário fazê-lo.
> 
> Bons estudos!

olá @Pliavi tudo bem?

Aula 08
Meu código está assim
<img width="586" alt="captura de tela 2019-01-08 as 18 46 00" src="https://user-images.githubusercontent.com/45274536/50857817-e5433880-1375-11e9-9662-6924af370615.png">
