### ISSUE TITLE
Por que instalar o Hyper no windows, se quando instalamos o Ubuntu ele já vem com o terminal?

### ISSUE THREAD

**Issue by jrmarqueshd** [CollabCodeTech/forum-do-front-ao-end#11]
Olá @MarcoBrunoBR, minha dúvida é, por que instalar o hyper, e não usar o terminal que ja vem padrão com o ubuntu? 

tem ferramentas a mais? ou é simplesmente por gosto?

**Comment by Pliavi** [comment]
Pelo que entendi é apenas uma recomendação, não alterará em nada utilizar outro emulador de terminal, seja o Gnome terminal que já vem no Ubuntu ou outro qualquer de outro sistema (seja o iTerm2 do Mac).

No máximo o que muda durante as aulas é o uso do ZSH, alguns comando que ele utilizou são de características dele:
 - Mostrar o repositório da pasta atual
 - Não utilizar o comando `cd` para andar pelas pastas.

Mas o Hyper em si não muda, é só questão de visual, ou talvez por o Hyper ter disponível para todas as distros, tanto Windows, Linux ou Mac e todos poderem ficarem com com um setup igual para a aula.

**Comment by jrmarqueshd** [comment]
Obg agora ficou bem claro!
