### ISSUE TITLE
Instalação do ZSH no terminal aula instalando zsh (windows)

### ISSUE THREAD

**Issue by malexxim** [CollabCodeTech/forum-do-front-ao-end#12]
Preciso de uma luz para a instalação do ZSH que está dando erro, segue o print, a família agradece
![zsh install](https://user-images.githubusercontent.com/34041868/48874111-a282cc80-edd8-11e8-9e00-738d6cd8e783.jpg)

**Comment by brunobolting** [comment]
Tenta rodar `sudo apt-get update` ou `sudo apt-get update --fix-missing`

**Comment by malexxim** [comment]
já fiz isso, é nervoso o negócio rsrsr

**Comment by Pliavi** [comment]
Tu tá rodando sob um proxy ou algum DNS fora do padrão?

Sendo positivo ou não, tente trocar temporariamente para o DNS do Google jogando o seguinte no terminal:
```
echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf > /dev/null
```
Pode ficar tranquilo, não vai alterar nada nas configurações do PC, ao reabrir o terminal essa mudança é sobreposta pro padrão novamente.

Após isso tente o `sudo apt update` e tente novamente.

**Comment by malexxim** [comment]
@brunobolting @Pliavi , muito obrigado, consegui resolver era um problema com  antivirus tren micro, quando desabilitei deu certo, valeu parceiros.
