### ISSUE TITLE
Como será feita a "entrega" dos desafios?

### ISSUE THREAD

**Issue by Pliavi** [CollabCodeTech/forum-do-front-ao-end#15]
Não pude acompanhar muito bem o Telegram hoje, mas vi que foi comentado sobre a entrega, teve o caso do print no chat.

Vi que @joviane deu a ideia de cada um fazer um repositório com os desafios feitos e de acordo com o tempo iam olhando, mas parei aí.

Então, que pé que deu? Vai ser pelo Telegram mesmo, por repositório, tem alguma forma certa de fazer de acordo com essas formas?

Obrigado :smiley:

**Comment by Morette** [comment]
eu não consegui acompanhar muito bem também, mas dei a seguinte ideia

Ser criada uma issue para cada aula/desafio e nós criamos um repositório. Quando concluirmos é só postar na issue o link para o repositório com a resposta.

Acho que assim facilita bastante para o @MarcoBrunoBR e @joviane porque vão saber certinho quando alguém concluir um desafio e o link
