### ISSUE TITLE
Aula 000 - Categorizar Dúvida no Fórum

### ISSUE THREAD

**Issue by Morette** [CollabCodeTech/forum-do-front-ao-end#16]
Olá,
acho que ainda não me deram permissão de <i>Write</i>. Procurei nos emails, mas não encontrei nada e não consigo criar/editar as labels.

😢

**Comment by Pliavi** [comment]
Não aparece aqui do lado?
![labels](https://i.imgur.com/3LG1K9G.png)

**Comment by MarcoBrunoBR** [comment]
> 
> 
> Olá,
> acho que ainda não me deram permissão de Write. Procurei nos emails, mas não encontrei nada e não consigo criar/editar as labels.
> 
> 😢

Desculpa pelo erro man. Acabei de te adicionar :-)

**Comment by Morette** [comment]
Agora sim.
Valeu man

:wink:
