### ISSUE TITLE
Como instalar o Hyper no Windows?

### ISSUE THREAD

**Issue by henribruno** [CollabCodeTech/forum-do-front-ao-end#2]
Estou tentando instalar o Hyper no Windows e está dando uns erros muitos doidos. Alguém tem um tutorial ou vídeo que ensine isso?

**Comment by lunajardim** [comment]
O @MarcoBrunoBR comentou que está gravando um vídeo sobre esse esquema aí de config do hyper no windows. Mas a galera do telegram já mandou esse link aqui que pode te ajudar: https://evdokimovm.github.io/windows/zsh/shell/syntax/highlighting/ohmyzsh/hyper/terminal/2017/02/24/how-to-install-zsh-and-oh-my-zsh-on-windows-10.html

**Comment by joviane** [comment]
> O @MarcoBrunoBR comentou que está gravando um vídeo sobre esse esquema aí de config do hyper no windows. Mas a galera do telegram já mandou esse link aqui que pode te ajudar: https://evdokimovm.github.io/windows/zsh/shell/syntax/highlighting/ohmyzsh/hyper/terminal/2017/02/24/how-to-install-zsh-and-oh-my-zsh-on-windows-10.html

Se você estiver usando o Mac, recomendo você usar um parada chamada iTerm. Da uma olhada no link e se tiver dúvida só chamar: https://www.iterm2.com

**Comment by joviane** [comment]
> O @MarcoBrunoBR comentou que está gravando um vídeo sobre esse esquema aí de config do hyper no windows. Mas a galera do telegram já mandou esse link aqui que pode te ajudar: https://evdokimovm.github.io/windows/zsh/shell/syntax/highlighting/ohmyzsh/hyper/terminal/2017/02/24/how-to-install-zsh-and-oh-my-zsh-on-windows-10.html

Se você estiver usando o Mac, recomendo usar o iTerm2, ele é bem feliz :-)
Ah! Ese é o link pra você baixar: https://www.iterm2.com

Apareceu uma dúvidas aí me avisa que tento ajudar!

**Comment by henribruno** [comment]
> 
> 
> O @MarcoBrunoBR comentou que está gravando um vídeo sobre esse esquema aí de config do hyper no windows. Mas a galera do telegram já mandou esse link aqui que pode te ajudar: https://evdokimovm.github.io/windows/zsh/shell/syntax/highlighting/ohmyzsh/hyper/terminal/2017/02/24/how-to-install-zsh-and-oh-my-zsh-on-windows-10.html

Obrigado Luna, ajudou muito o link, não vou precisar esperar o Marco fazer o vídeo :-)
