### ISSUE TITLE
Problemas com login

### ISSUE THREAD

**Issue by joviane** [CollabCodeTech/forum-do-front-ao-end#25]
Pessoal,

Se alguém tiver problemas para logar no site me avisem com o e-mail de vocês aqui e com a mensagem que está aparecendo para eu poder ver o mais rápido possível.

**Comment by CristianoMorgante** [comment]
cristianomorgante@hotmail.com

"Mal aí! Ainda não temos cursos free!"

**Comment by robsonribeiros** [comment]
![captura de tela de 2018-11-22 11-06-09](https://user-images.githubusercontent.com/25713975/48907676-e7dde300-ee46-11e8-8e9e-79f475e791eb.png)
Ao logar o meu dashboard fica assim conforme imagem
>email: robsont36@gmail.com

**Comment by robsonribeiros** [comment]
Agora tá feliz :)

**Comment by FeelipePM** [comment]
Também estou com este mesmo problema acima.
email: feelipe@email.com

**Comment by joviane** [comment]
> Também estou com este mesmo problema acima.
> email: [feelipe@email.com](mailto:feelipe@email.com)

Fê, seu e-mail que está com acesso é: Feelipe.PM@gmail.com dá uma olhada?

**Comment by FeelipePM** [comment]
> > Também estou com este mesmo problema acima.
> > email: [feelipe@email.com](mailto:feelipe@email.com)
> 
> Fê, seu e-mail que está com acesso é: [Feelipe.PM@gmail.com](mailto:Feelipe.PM@gmail.com) dá uma olhada?

na verdade eu fiz cagada, eu não cadastrei esse e-mail, vou ver se boto recuperar senha.

**Comment by FeelipePM** [comment]
cadastrei o email Feelipe.PM@gmail.com, está funcionando, só libera o acesso feliz =D

**Comment by anacunha** [comment]
Ao tentar logar com meu email (mcunha.ana@gmail.com), recebo a seguinte mensagem:

> Por favor, valide seu e-mail antes de fazer login

Se eu tento me cadastrar, diz que meu e-mail já está cadastrado.

Também tentei resetar a senha e o mesmo problema continua acontecendo.

Obrigada! :)

**Comment by joviane** [comment]
> Ao tentar logar com meu email ([mcunha.ana@gmail.com](mailto:mcunha.ana@gmail.com)), recebo a seguinte mensagem:
> 
> > Por favor, valide seu e-mail antes de fazer login
> 
> Se eu tento me cadastrar, diz que meu e-mail já está cadastrado.
> 
> Também tentei resetar a senha e o mesmo problema continua acontecendo.
> 
> Obrigada! :)

Ana,

Tenta colocar o e-mail sem o . ? mcunhaana@gmail.com

**Comment by anacunha** [comment]
> > Ao tentar logar com meu email ([mcunha.ana@gmail.com](mailto:mcunha.ana@gmail.com)), recebo a seguinte mensagem:
> > > Por favor, valide seu e-mail antes de fazer login
> > 
> > 
> > Se eu tento me cadastrar, diz que meu e-mail já está cadastrado.
> > Também tentei resetar a senha e o mesmo problema continua acontecendo.
> > Obrigada! :)
> 
> Ana,
> 
> Tenta colocar o e-mail sem o . ? [mcunhaana@gmail.com](mailto:mcunhaana@gmail.com)

Tentei sem o ponto e deu a mesma coisa, tanto no cadastro quanto no login :\

<img width="396" alt="screen shot 2018-11-22 at 12 56 14" src="https://user-images.githubusercontent.com/1771610/48910063-24fda180-ee56-11e8-87d3-151b0bdfb638.png">

**Comment by jrmarqueshd** [comment]
gilmar_junior@hotmail.com.br nunca consigo nada nessa vda dura :( kkk

**Comment by krivax** [comment]
Meu e-mail krivahz@gmail.com

**Comment by joviane** [comment]
> 
> 
> [gilmar_junior@hotmail.com.br](mailto:gilmar_junior@hotmail.com.br) nunca consigo nada nessa vda dura :( kkk

Dá uma olhada se foi agora @jrmarqueshd ?

**Comment by joviane** [comment]
> 
> 
> > > Ao tentar logar com meu email ([mcunha.ana@gmail.com](mailto:mcunha.ana@gmail.com)), recebo a seguinte mensagem:
> > > > Por favor, valide seu e-mail antes de fazer login

Oi @anacunha aqui estava faltando confirmar o e-mail mesmo. Você deve ter recebido um e-mail de confirmação mas acabei de liberar aqui. Tenta acessar novamente sem o . ?

**Comment by anacunha** [comment]
> > > > Ao tentar logar com meu email ([mcunha.ana@gmail.com](mailto:mcunha.ana@gmail.com)), recebo a seguinte mensagem:
> > > > > Por favor, valide seu e-mail antes de fazer login
> 
> Oi @anacunha aqui estava faltando confirmar o e-mail mesmo. Você deve ter recebido um e-mail de confirmação mas acabei de liberar aqui. Tenta acessar novamente sem o . ?

Resolvido! Valeu :)

**Comment by emllbrt** [comment]
Ao logar aparece essa tela
email: emille.sbrito@gmail.com

![tela](https://user-images.githubusercontent.com/27964963/48923038-2c42a080-ee92-11e8-8093-451d933083dc.png)

**Comment by joviane** [comment]
O da Emille também está resolvido. :-)
