### ISSUE TITLE
Diferença dos commits:  "-am", "-m" e "-a"

### ISSUE THREAD

**Issue by DaniloSouzaDev** [CollabCodeTech/forum-do-front-ao-end#26]
No primeiro vídeo sobre Git eu percebi que quando o arquivo da aula 002.md foi criado e foi dado o "git status" o terminal sugeriu dar um "git add ou git commit -a", mas para exemplificar e apenas guardar o que foi modificado no arquivo que já estava sendo trackeado (o arquivo 002 não estava) o @marco deu um "git commit -am". A dúvida é: O que significa esses "-am", "-a" e "-m"? Qual a diferença?

**Comment by FeelipePM** [comment]
git commit -m "suaMensagem" - serve para você commitar seu arquivo com a mensagem especifica para ele ficar preparado para dar push.

git commit -a - serve para preparar automaticamente os arquivos que foram modificados e excluídos, mas os novos arquivos que você não informou ao Git não serão afetados.

git commit -am "suaMensagem" - Ele já adiciona e comita ao mesmo tempo

**Comment by Pliavi** [comment]
![a](https://i.imgur.com/Nfg3Ay9.png)

o `git commit -a` é o mesmo que você dar dois comandos em um:
```sh
# O commit é executado após o add
git add -u && git commit 
```
> Perceba que a opção `-u` significa que ele _trackeará_ arquivos modificados e deletados, mas não adicionará arquivos novos

![m](https://i.imgur.com/Ty58J97.png)
Já o `git -m` significa que você quer mandar uma mensagem no commit, mas como a mensagem é obrigatória, se você não passar nada ele abrirá o Vim ou o Nano pra você escrever a mensagem.
Exemplos de uso:
```sh
git -m "mensagem"
git -m "isso é um paragrafo" "esse é outro"
git -m "Isso é um paragrafo
> E isso também"

git -m
```

Opções com apenas um traço geralmente são contrações e podem ser concatenadas e usadas juntas, então `-am` significa nada mais que ele está adicionando arquivos e escrevendo uma mensagem de uma vez.

**Comment by MarcoBrunoBR** [comment]
Caramba! Comunidade Show! Consegui resolver sua dúvida @DaniloSouzaDev ? -- perguntando só pra marcar como resolvido ou tirar qualquer dúvida que você tenha ficado :-)
