### ISSUE TITLE
#001Aula - Desafios

### ISSUE THREAD

**Issue by DaniloSouzaDev** [CollabCodeTech/forum-do-front-ao-end#28]
**Link -> [Desafios aula 001](https://github.com/DaniloSouzaDev/bloco-de-anotacoes/blob/master/Desafios/desafios-aula-001.md)**

**001 - [Desafio Básico](https://github.com/DaniloSouzaDev/bloco-de-anotacoes/commit/77257c329b5ccc400a5415525427df513bcb4f22)**
**001 - [Desafio Intermediário](https://github.com/DaniloSouzaDev/bloco-de-anotacoes/commit/b94bf92dde5116441e73035bb20a3af3f3bf9dda)**
**001 - [Desafio Avançado](https://github.com/DaniloSouzaDev/bloco-de-anotacoes/commit/ea9d20db82af0abb37ed89eb7b9fbe09cb25a339)**

@MarcoBrunoBR 
@joviane

**Comment by DaniloSouzaDev** [comment]
> **[001] - Desafio Básico]([DaniloSouzaDev/bloco-de-anotacoes@aa612e6#diff-5b94a7d3eab855f26cf55f089f5d82d6](https://github.com/DaniloSouzaDev/bloco-de-anotacoes/commit/aa612e656841123a59595164809546c9190d5ae8#diff-5b94a7d3eab855f26cf55f089f5d82d6))**
> **[001] - Desafio Intermediário]([DaniloSouzaDev/bloco-de-anotacoes@b94bf92#diff-5b94a7d3eab855f26cf55f089f5d82d6](https://github.com/DaniloSouzaDev/bloco-de-anotacoes/commit/b94bf92dde5116441e73035bb20a3af3f3bf9dda#diff-5b94a7d3eab855f26cf55f089f5d82d6))**
> **[001] - Desafio Avançado]([DaniloSouzaDev/bloco-de-anotacoes@ea9d20d#diff-5b94a7d3eab855f26cf55f089f5d82d6](https://github.com/DaniloSouzaDev/bloco-de-anotacoes/commit/ea9d20db82af0abb37ed89eb7b9fbe09cb25a339#diff-5b94a7d3eab855f26cf55f089f5d82d6))**
> 
> @MarcoBrunoBR
> @joviane

No desafio básico que era só trocar o tema do hyper, eu tentei colocar a imagem aqui no github usando markdown e parece que não foi.

**Comment by CarloosBR** [comment]
Repositório com os desafios: https://github.com/CarloosBR/bloco-de-anotacoes/tree/master/desafios
@MarcoBrunoBR @joviane

**Comment by DaniloSouzaDev** [comment]
> **Link -> [Desafios aula 001](https://github.com/DaniloSouzaDev/bloco-de-anotacoes/blob/master/Desafios/desafios-aula-001.md)**
> 
> **001 - [Desafio Básico](https://github.com/DaniloSouzaDev/bloco-de-anotacoes/commit/77257c329b5ccc400a5415525427df513bcb4f22)**
> **001 - [Desafio Intermediário](https://github.com/DaniloSouzaDev/bloco-de-anotacoes/commit/b94bf92dde5116441e73035bb20a3af3f3bf9dda)**
> **001 - [Desafio Avançado](https://github.com/DaniloSouzaDev/bloco-de-anotacoes/commit/ea9d20db82af0abb37ed89eb7b9fbe09cb25a339)**
> 
> @MarcoBrunoBR
> @joviane

é para postar do jeito que fiz no início ou separado como fiz logo depois?

**Comment by heliorlz** [comment]
# Desafios Aula 001

- [001] - [Desafio Intermediário](https://github.com/heliorlz/desafiosCollabCode/commit/fc5b6eb6cf68c0d3607a90ad65b0aad12e67fbae)
- [001] - [Desafio Avançado](https://github.com/heliorlz/desafiosCollabCode/commit/3c16a5886fa1029261775c507446ce6899d8f829)

**Comment by sarival** [comment]
# Desafios Aula 001
1. Desafio intermediário - [link](https://github.com/sarival/bloco-de-anotcaoes)
1. Desafio avançado - [link](https://github.com/sarival/bloco-de-anotcaoes/commit/5c79ac382a9d4517c6e1a10015ba9e7647954000)

**Comment by RaphaelOhlsen** [comment]
1. [Desafio Intermediário e Avançado](https://github.com/RaphaelOhlsen/bloco-de-anotacoes/blob/master/aulas/001.md)

**Comment by LuizRamos19** [comment]
Seguem desafios da aula 001

[Desafio intermediário](https://github.com/LuizRamos19/bloco-de-anotacoes/commit/afe1f99dbbdaef69a3ecd8f86533ac05f700e4a1)
[Desafio avançado](https://github.com/LuizRamos19/bloco-de-anotacoes/commit/f50029dfd3fa537f9bd8a535544ffe8c882a33e7)

@MarcoBrunoBR 
@joviane

**Comment by CamilaPimenta** [comment]
*Desafios da aula 001*
 - https://github.com/CamilaPimenta/desafiosCollabCode

@joviane @MarcoBrunoBR

**Comment by isapires** [comment]
Desafios da aula 001

https://github.com/isapires/desafios/tree/master/aula001

**Comment by fredcsouza** [comment]
Desafios da aula 001

https://github.com/fredcsouza/CollabCode-Desafios/tree/master/001

**Comment by bruno1902** [comment]
Desafio 001
--> https://github.com/bruno1902/Aula-001-markdown-git-/blob/master/README.md

**Comment by divetta** [comment]
[Desafios 001](https://github.com/divetta/bloco-de-anotacoes/blob/master/aulas/001.md)

**Comment by leopeli** [comment]
https://github.com/leopeli/do-front-ao-end-desafios/tree/master/aula-1

@MarcoBrunoBR 
@joviane

**Comment by PabloFerreiraB** [comment]
## Desafio `Aula-001`
https://github.com/PabloFerreiraB/do-front-ao-end/tree/master/aulas/desafio-001

**Comment by carlosevandro** [comment]
[[001] desafio-básico](https://github.com/carlosevandro/bloco-de-anotacoes/blob/master/aulas/aula_001/desafio1_aula001.PNG)
[[001] desafio-intermediário](https://github.com/carlosevandro/bloco-de-anotacoes/blob/master/aulas/aula_001/desafio2_aula001.md)
[[001] desafio-avançado](https://github.com/carlosevandro/bloco-de-anotacoes/blob/master/aulas/aula_001/desafio3_aula001.md)

@MarcoBrunoBR , @joviane

**Comment by fpsaraiva** [comment]
Não havia visto essa issue antes, acabei não seguindo muito bem a ordem dos commits :grin: Os desafios estão [neste](https://github.com/fpsaraiva/curso-do-front-ao-end/tree/master/aula%2001) repositório.

**Comment by emllbrt** [comment]
[**Desafios da aula 001**](https://github.com/emllbrt/do-front-ao-end/tree/master/desafios)

@MarcoBrunoBR
@joviane

**Comment by felipecamargo8** [comment]
[Desafio 001](lhttps://github.com/felipecamargo8/bloco-de-anotacoes/blob/master/aulas/Desafiofacil.png)

[Desafio 002](https://github.com/felipecamargo8/bloco-de-anotacoes/blob/master/aulas/001Desafiointer.md)

[Desafio 003](https://github.com/felipecamargo8/bloco-de-anotacoes/blob/master/aulas/Desafiofacil.png)

@MarcoBrunoBR 
@joviane
