### ISSUE TITLE
Formatação no Markdown

### ISSUE THREAD

**Issue by Wanhenri** [CollabCodeTech/forum-do-front-ao-end#29]
Existe algum meio de colocar duas figuras lado a lado no markdown?

**Comment by Wanhenri** [comment]
Fiz um teste com algumas figuras e não deram certo. Será que foi por causa do tamanho das figuras?

https://github.com/Wanhenri/collab_curso_2018_19/blob/master/aula002/desafio_2/teste.md
usei a mesma estrutura que você utilizou:
```
[alt text][logo1] ![alt text][logo2]

[logo1]:https://github.com/Wanhenri/JupNcl_serie_temporal/blob/master/img/teste_SMG_v200.png "versao 2.0.0"
[logo2]:https://github.com/Wanhenri/JupNcl_serie_temporal/blob/master/img/teste_SMG_v210.png "versao 2.1.0"
```

**Comment by FeelipePM** [comment]
<img src="https://gyazo.com/eb5c5741b6a9a16c692170a41a49c858.png" width="200" height="400" /> <img src="https://gyazo.com/eb5c5741b6a9a16c692170a41a49c858.png" width="200" height="400" />

daria para setar o tamanho fazer dessa forma

`<img src="https://gyazo.com/eb5c5741b6a9a16c692170a41a49c858.png" width="200" height="400" /> <img src="https://gyazo.com/eb5c5741b6a9a16c692170a41a49c858.png" width="200" height="400" />`

**Comment by Wanhenri** [comment]
Excelente!!!!!!Funcionou perfeitamente!!! Muito obrigado pela ajuda.
