### ISSUE TITLE
Links úteis por tópicos (em ordem alfabética)

### ISSUE THREAD

**Issue by FeelipePM** [CollabCodeTech/forum-do-front-ao-end#3]
# Tópicos

- CSS
- Git
- Github
- HTML
- Hyper
- Javascript
- Markdown
- [Terminal](https://github.com/CollabCodeTech/forum-do-front-ao-end/issues/3#issuecomment-440095805 "Clique e acesse agora!")

**Comment by heliorlz** [comment]
Valeu , muito bom

**Comment by MarcoBrunoBR** [comment]
> 
> 
> [Instalação do Zsh e oh My Zsh no Windows 10](https://evdokimovm.github.io/windows/zsh/shell/syntax/highlighting/ohmyzsh/hyper/terminal/2017/02/24/how-to-install-zsh-and-oh-my-zsh-on-windows-10.html)
> 
> [Configuração do Hyper by MarcoBrunoBR](https://notepad.pw/share/06tx422h)
> 
> [Fórum - Do Front ao End](https://github.com/CollabCodeTech/forum-do-front-ao-end)

Top top top

**Comment by gregolly** [comment]
Muito bom amigo!!!

**Comment by theuzlt** [comment]
Como aplico Configuração no Hyper?

**Comment by gregolly** [comment]
> Como aplico Configuração no Hyper?

theuzlt acredito que o marco usou esse link: https://evdokimovm.github.io/windows/zsh/shell/syntax/highlighting/ohmyzsh/hyper/terminal/2017/02/24/how-to-install-zsh-and-oh-my-zsh-on-windows-10.html

**Comment by FeelipePM** [comment]
# Terminal

- [Instalação do Zsh e oh My Zsh no Windows 10](https://evdokimovm.github.io/windows/zsh/shell/syntax/highlighting/ohmyzsh/hyper/terminal/2017/02/24/how-to-install-zsh-and-oh-my-zsh-on-windows-10.html "Clique e acesse agora!")

- [Configuração do Hyper by MarcoBrunoBR](https://notepad.pw/share/06tx422h "Clique e acesse agora!")

- [Aprendendo mais sobre Markdwon](https://markdown.showmethecode.com.br "Clique e acesse agora!")

**Comment by FeelipePM** [comment]
Agora pode ser acessado - https://github.com/CollabCodeTech/forum-do-front-ao-end/blob/master/links-uteis.md

**Comment by joviane** [comment]
Vou fechar essa issue aqui porque acho que a galera já se acostumou com o lugar onde estão os links
