### ISSUE TITLE
Aula 001 Usando GitHub - erro no git push -u origin master

### ISSUE THREAD

**Issue by Morette** [CollabCodeTech/forum-do-front-ao-end#30]
Quando dei o git push -u origin master apareceu o erro abaixo

![image](https://user-images.githubusercontent.com/20028647/48924829-9879d000-eea3-11e8-993c-1bd7ff466baf.png)

Precisei forçar com -f o push para enviar para o GitHub.
Já aconteceu isso outras vezes, mas nunca entendi o motivo do erro.

Alguém sabe dizer?

**Comment by diegovbarros** [comment]
Você tem que fazer o `git pull` pra pegar a versão atual do git e fazer o merge com a versão da máquina. Maioria das vezes o merge acontece automaticamente, dai é só commitar e dar o push normalmente. Porém as vezes você terá que fazer o merge manual, pra evitar isso ao máximo, sempre execute um `git pull` antes de começar a trabalhar na versão local, principalmente quando estiver trabalhando em um projeto com uma equipe grande, pois irão acontecer vários pushs sem que você tome conhecimento.

**Comment by Morette** [comment]
> você iria dar apenas git pull, ai ele iria puxar as atualizações lá do seu repósitorio, e depois poderia dar o git push, isso se os arquivos ja estiver commitados.

Eu fiz isso, mas o git pull dava o mesmo erro do git push.

**Comment by FeelipePM** [comment]
Salva o projeto novamente, deleta a pasta dele do github e abre ela denovo lá e coloca os arquivso principais e depois as alterações, sei que vai dar um trabalho mais deve resolver.

**Comment by Morette** [comment]
Forçando com o <b><i>git -f push origin master</i></b> eu já consegui enviar para o GitHub.

Agora está normal, eu só queria entender porque fazendo na mesma sequência do Marco no vídeo o meu apresentou esse problema e o dele não.

**Comment by FeelipePM** [comment]
Você fez o git remote add origin?

**Comment by MarcoBrunoBR** [comment]
> 
> 
> Forçando com o git -f push origin master eu já consegui enviar para o GitHub.
> 
> Agora está normal, eu só queria entender porque fazendo na mesma sequência do Marco no vídeo o meu apresentou esse problema e o dele não.

Se no momento que você criou o repo marcou a opção **Initialize this repository with a README** é necessário você realizar o `clone` e depois começar o seu projeto com esse clone ou será necessário você primeiro realizar o `pull` e depois você irá conseguir realizar o `push`. Por que isso acontece?

![capturar](https://user-images.githubusercontent.com/4096456/48999085-b2820f80-f13c-11e8-8564-29456d128e20.PNG)

Quando você cria o repo e marca a opção **Initialize this repository with a README** o seu repo remoto que está no github já tem um conteúdo dentro dele e o seu repo local não tem nada inicialmente. Quando você começa colocar o conteúdo no seu repo local e fazer os seus commits locais nada de problema acontece, mas no momento que você quer enviar esses commits para o seu repo remoto o remoto por sua vez tem uma informação de um commit que não tem no seu repo local. Por isso que na mensagem que você recebeu de erro, ela solicita que você antes realizar o comando `git pull` para trazer o `commit` do repo remoto e deixar o históricos dos commits tanto do local quanto do remoto iguais e ai em seguida você poderá enviar os commits ao repo remoto que você fez no seu local.

Quando você executou o `git -f push origin master` você resolveu ignorar a diferença que tinha do repo remoto com o local ;-)
Pra esse caso não tem problema nenhum, mas tome muito cuidado a fazer isso, mas pra frente isso ficará mais claro, ficará realmente claro no momento que você for parear com outro aluno 👍

**Comment by Morette** [comment]
Ah, agora entendi...
Realmente eu havia iniciado com um readme.

Valeu

**Comment by Lenonnn** [comment]
Pra mim aparece isso também e não consigo resolver isso! Alguém poderia mastigar mais ? 

Hehehehehehehehe

**Comment by FeelipePM** [comment]
Lenonnn da um git pull e depois da o git push -u origina master

**Comment by Lenonnn** [comment]
FeelipePM tentai várias vezes, e dá sempre o mesmo erro, já fiz o git pull e o git push pra fazer tenatar fazer o pushing e não dá certo

**Comment by angelica-soares** [comment]
Estou com o mesmo problema. Eu inicializo com README.md, mas como orientado em cima, o git pull não rolou. Só funciona se eu dou git push -f origin master...

**Comment by FeelipePM** [comment]
Caso não tenha feito nenhuma alteração da para deletar e usar um git clone novamente. o `git push  -f origin master` funcionou para você angelica?

**Comment by henriquefontenele** [comment]
estou com esse mesmo problema...

**Comment by rafaelmpardim** [comment]
No meu caso, quando realizo o comando "git push origin main", o GIT deveria abrir a tela para inserção da senha do GITHUB, porém o terminal não executa ação nenhuma. Estou trabalhando com repositório HTTPS. Usando o SSH já consegui. Alguém sabe me dizer por que não funciona com HTTPS?

**Comment by Nedhard** [comment]
> No meu caso, quando realizo o comando "git push origin main", o GIT deveria abrir a tela para inserção da senha do GITHUB, porém o terminal não executa ação nenhuma. Estou trabalhando com repositório HTTPS. Usando o SSH já consegui. Alguém sabe me dizer por que não funciona com HTTPS?

estou com mesmo problema que voce e nao consigo resolver

**Comment by brunobolting** [comment]
@orafapardim @Nedhard 
Da uma olhada se vocês estão utilizando a url correta, existe uma para o SSH e outra para HTTPS:
![Captura de tela de 2021-06-28 14-06-19](https://user-images.githubusercontent.com/33732209/123676440-50b94300-d81a-11eb-9546-53e549d72e39.png)
Vocês podem usar o comando `git remote set-url` para trocar a url do repositório. Para pedir usuário e senha a url deve ser no formato do HTTPS

**Comment by rafaelmpardim** [comment]
Obrigado, Bruno. Consegui resolver.
Estava com a URL correta, porém havia uma falha na instalação do GIT. Desinstalei e instalei novamente e agora funciona perfeitamente!

Muito obrigado pela ajuda!!

**Comment by grcustodio** [comment]
O que me ajudou foi esse vídeo... https://youtu.be/E28J23gCBIs


Abraço!


> No meu caso, quando realizo o comando "git push origin main", o GIT deveria abrir a tela para inserção da senha do GITHUB, porém o terminal não executa ação nenhuma. Estou trabalhando com repositório HTTPS. Usando o SSH já consegui. Alguém sabe me dizer por que não funciona com HTTPS?
