### ISSUE TITLE
Aula 001- Desafios

### ISSUE THREAD

**Issue by LuizRamos19** [CollabCodeTech/forum-do-front-ao-end#31]
Seguem desafios da aula 001

[Desafio intermediário](https://github.com/LuizRamos19/bloco-de-anotacoes/commit/afe1f99dbbdaef69a3ecd8f86533ac05f700e4a1)
[Desafio avançado](https://github.com/LuizRamos19/bloco-de-anotacoes/commit/f50029dfd3fa537f9bd8a535544ffe8c882a33e7)

@MarcoBrunoBR 
@joviane

**Comment by DaniloSouzaDev** [comment]
> Seguem desafios da aula 001
> 
> [Desafio intermediário](https://github.com/LuizRamos19/bloco-de-anotacoes/commit/afe1f99dbbdaef69a3ecd8f86533ac05f700e4a1)
> [Desafio avançado](https://github.com/LuizRamos19/bloco-de-anotacoes/commit/f50029dfd3fa537f9bd8a535544ffe8c882a33e7)
> 
> @MarcoBrunoBR
> @joviane

@LuizRamos19  já existe uma issue do desafio. Posta lá.
