### ISSUE TITLE
[Aula - 002][Dúvida] -  Semântica

### ISSUE THREAD

**Issue by diegovbarros** [CollabCodeTech/forum-do-front-ao-end#33]
Tenho uma dúvida em relação a semântica. Você explicou sobre o <a></> e disse que era pra ser usado ao linkar com outros documentos internos ou externos. Porém já muitas vezes a tag button ser usada para o mesmo fim. 
Então eu pergunto. Quando usar <a> e quando usar <button> e suas variações de type semânticamente falando?

**Comment by FeelipePM** [comment]
A tag `<button>` é usada quando você tem um contexto de um botão clicável, por exemplo em um formulário, ela pode ser usada também quando ela tem algum objetivo, seja pegar um input, ou fazer alguma função.

a tag `</>` usamos como âncora, referência aquele nosso elemento pra outro lugar. no caso do nosso menu de navegação.

Diego, fez sentido?

**Comment by diegovbarros** [comment]
Sim faz sentido. Obrigado.

Então quando alguém usa um botão pra fazer a função de um link, semânticamente isso é errado certo? Existe algum motivo de usarem tanto um button no lugar de um link? Seja alguma funcionalidade ou estilo que o button provê e o link não?

**Comment by FeelipePM** [comment]
Sim, semanticamente é errado.

acredito que a maioria use porque já entrega a  forma de um botão bonitinho, o <a> você teria que fazer um css um pouco mais trabalhado.

imaginei você tem um site e você cria um `<button>`para cair em outro página, na verdade você criou um hiperlink que usaria a tag de semântica `<a>` que seria a semântica correta.

continua fazendo sentido pra você?

**Comment by FeelipePM** [comment]
https://validator.w3.org/

Essse site é um validador semântico, dá uma olhada.

**Comment by diegovbarros** [comment]
Saquei. Valeu pela resposta e pela dica do site
