### ISSUE TITLE
Correção dos desafios

### ISSUE THREAD

**Issue by Wanhenri** [CollabCodeTech/forum-do-front-ao-end#36]
Qual local será disponibilizado a correção/comentários dos desafios?

**Comment by MarcoBrunoBR** [comment]
Estou respondendo no próprio lugar onde você postou o desafio. Até o momento respondi poucas pessoas. Mas hoje vou trabalhar nisso pra responder ainda mais pessoas. Recomendo que mesmo que eu não tenha chegado em seu desafio você dar uma olhada nas respostas que eu já dei porque da pra aprender muito com elas :-)

**Comment by Wanhenri** [comment]
Desculpa a demora. Muito obrigado pela ajuda.
