### ISSUE TITLE
Problemas com a NodeJS e NPM após instalação do ZSH

### ISSUE THREAD

**Issue by FabricioAKawano** [CollabCodeTech/forum-do-front-ao-end#37]
Após a instalação do ZSH estou tendo problemas no terminal com os comandos do NodeJS e NPM, ao executar o comando 'npm --version' apresenta a mesagem abaixo com forme o print:
![image](https://user-images.githubusercontent.com/7452531/48971369-99c00f80-efff-11e8-8ed0-85fca0719772.png)

**Comment by MarcoBrunoBR** [comment]
Caraka. Tive o mesmo problema quando fiz a config na minha máquina. Mas isso faz um tempo então posso estar te dando a dica errada.

Mas o que eu fiz foi ir até o terminal do ubuntu e instalar o nodejs novamente no ambiente ubuntu. Tenta fazer isso e vê se volta a aceitar os comandos normalmente :-)

**Comment by FabricioAKawano** [comment]
Vlw @MarcoBrunoBR , instalação do node e npm no ubuntu resolveu o problema
