### ISSUE TITLE
Problema com a configuração do Hyper 

### ISSUE THREAD

**Issue by tjcm** [CollabCodeTech/forum-do-front-ao-end#39]
Boa tarde, segui todo o tutorial do Marco pra configuração do bash, mas no passo final ele não funciona.

quando tento dar o `bash -c zsh` ele não muda do bin bash para o zsh

segue print
![image](https://user-images.githubusercontent.com/37338357/48983835-a2cde100-f0d2-11e8-986a-ebc5be7a3f76.png)
 Editei o arquivo no ubuntu, e no ubuntu eu consigo entrar no zsh, mas não no hyper.

**Comment by MarcoBrunoBR** [comment]
Acabei de ver aqui. Isso não é um erro na verdade, o que acontece é que o comando `bash -c zsh` não muda a variável de ambiente `$SHELL`. Mas você pode ver que os comando do zsh estão funcionando e você conseguiu mudar o tema do zsh de boas :-)

**Comment by FeelipePM** [comment]
@tjcm  sua dúvida foi resolvida?
