### ISSUE TITLE
Problema Trava o Terminal e fica (END) (Mesma coisa que aconteceu na aula gravada)

### ISSUE THREAD

**Issue by opabloteixeira** [CollabCodeTech/forum-do-front-ao-end#40]
Ocorreu algumas vezes quando o Marco estava gravando as aulas, alguém descobriu porque?

No meu caso foi quando fui dar git log, mostrou as informações e travou, ficou o (END)

![errolog](https://user-images.githubusercontent.com/13955134/48988163-260b2900-f10b-11e8-9b89-1d4ddc52fd4e.jpg)

**Comment by opabloteixeira** [comment]
Descobri, aperta tecla "Q" pra sair

**Comment by AdalbertoGarc** [comment]
No meu apertei apenas "q", tenta pra vê se funciona.

> Assim que entrar vc aperta que (q), ai sai.
