### ISSUE TITLE
Bloco de anotações - VSCode - MAC

### ISSUE THREAD

**Issue by lianebez** [CollabCodeTech/forum-do-front-ao-end#42]
Olá.

Estou tentando fazer o comando code . na pasta bloco-de-anotacoes no iTerm e está dizendo que esse comando não existe. 

 ╭─lianebez@Lianes-MacBook-Pro ~/do-front-ao-end/bloco-de-anotacoes
╰─$ code .                                                                127 ↵
zsh: command not found: code

**Comment by Pliavi** [comment]
Abra o VSCode, aperte CMD+P, tente desinstalar e reinstalar o code no PATH.
![](https://i.stack.imgur.com/m2v5w.png)

**Comment by lianebez** [comment]
Funcionou. Muito obrigada
