### ISSUE TITLE
Dúvida sobre versionamento

### ISSUE THREAD

**Issue by bruno1902** [CollabCodeTech/forum-do-front-ao-end#43]
Pessoal, 
Ontem quando fui fazer o desafio-002, percebi que estava com problemas para "subir" as respostas :
""Desafio--001 -- Desafio--002--  Desafio--003  ""
Deixando claro, não tive problemas com o git em si, acho que consegui aprender o que cada comando faz. O problema foi saber como usar.
-- Vocês criaram um repositório para a atividade toda e foram versionando cada parte do desafio??
Isso que não peguei a ideia 👎

**Comment by heliorlz** [comment]
Na verdade eu commitei cada desafio, e colei a url de cada commit, por exemplo, fiz o desafio 1 da aula 2 e subi pro git, fiz o desafio 2 e subi pro git, aí na área dos commits feitos, fica separado por desafio, pegou? Acho que é isso que todos estão fazendo

**Comment by diegosparente** [comment]
Oi Bruno!

É como heliorlz falou. Você pode fazer um desafio, por exemplo, desafio001 e fazer o commit dele. Aí antes de você realizar o próximo desafio já da pra copiar a url do commit referente ao desafio001 e usar o Markdown pra registrar! 😊

**Comment by bruno1902** [comment]
legal!!
Acho que peguei a ideia, obg a a todos!

**Comment by CristianoMorgante** [comment]
Estou colocando o link do meu repositório com os commit's separado por nome. 
Ex:
[002] Desafio Basico
[002] Desafio Intermediário
[002] Desafio Avançado

Mas pelo que eu entendi o que o Marco pediu, e a Jovi tbm disse, não há necessidade de criar links para cada um deles.(Se entendi errado desculpa @MarcoBrunoBR @joviane ).
Somente o link do repositório e os commit's separados.
