### ISSUE TITLE
Estou apanhando para chegar no meu diretório para criar uma pasta no hyper, comprei outro computador fazendo novamente, no outro tinha feito pelo powershell

### ISSUE THREAD

**Issue by washics18** [CollabCodeTech/forum-do-front-ao-end#44]
Não estou conseguindo chegar no C para depois colocar mkdir e a pasta que vou criar.
![image](https://user-images.githubusercontent.com/45200025/49014740-e15dad00-f15f-11e8-8f4a-0cd49a975b4b.png)

**Comment by diegosparente** [comment]
Oi washics18!

Na imagem que você adicionou mostra que você conseguiu acessar o diretório `/mnt/c`. Qual a mensagem que aparece quando você usa o `mkdir`?

```
mkdir <nome_da_pasta>
```

**Comment by washics18** [comment]
Aparece assim:
![image](https://user-images.githubusercontent.com/45200025/49015430-d572ea80-f161-11e8-9008-e480240981ab.png)

**Comment by diegosparente** [comment]
Vamos tentar assim:

```
mkdir -p /mnt/c/do-front-ao-end
```

**Comment by diegosparente** [comment]
Valeu pelas dicas @Pliavi =D

Tomará que @washics18 tenha resolvido!

**Comment by washics18** [comment]
Consegui abrir pelo hyper !! Valeu pela ajuda pessoal. Abraços
![image](https://user-images.githubusercontent.com/45200025/49020209-a8790480-f16e-11e8-871d-06574850d01a.png)
