### ISSUE TITLE
Desafio Avançado Aula 002 - background-color

### ISSUE THREAD

**Issue by Morette** [CollabCodeTech/forum-do-front-ao-end#47]
Olá,
consegui fazer o posicionamento do desafio, porém o background-color não cobre todo H1.

A tag header onde coloquei a propriedade está com o mesmo tamanho da tag nav, fazendo a cor de fundo ficar pela metade.

Como coloquei a propriedade na tag pai, não deveria cobrir tudo que esta tag engloba?

![image](https://user-images.githubusercontent.com/20028647/49048402-b9069a80-f1c1-11e8-9c42-f65fe49b6006.png)

**Comment by icastilhog** [comment]
Você precisa usar o overflow: hidden;
no seu header no css.. o Marco explicou o porque desse comportamento de cortar.. é porque a propriedade float tem o comportamento de tirar do elemento pai.. então no momento que você colocou o float no h1, ele saiu do elemento pai, então o background color ficou apenas para o nav.. o nav subiu porque o float foi pra "frente".. então temos que usar esse overflow: hidden para ele recalcular o tamanho dos dois.

é um pouco complicado explicar rs
No vídeo float de uma forma feliz ele explica sobre isso..

**Comment by GuiiMoraes** [comment]
Fala, @Morette 
Usa a propriedade overflow: hidden que vai fazer com que o pai pegue o tamanho do h1
O Marco explica melhor na aula, mas isso ocorre por causa do uso do float, usando o overflow ele vai conseguir calcular o tamanho do h1 e qualquer outra tag com o float

**Comment by Morette** [comment]
> Você precisa usar o overflow: hidden;
> no seu header no css.. o Marco explicou o porque desse comportamento de cortar.. é porque a propriedade float tem o comportamento de tirar do elemento pai.. então no momento que você colocou o float no h1, ele saiu do elemento pai, então o background color ficou apenas para o nav.. o nav subiu porque o float foi pra "frente".. 

o uso de `display: inline-block` não deveria corrigir esse comportamento?

**Comment by icastilhog** [comment]
o display: inline-block quando usado ele alinha os elementos e mantém o tamanho padrão deles.. mas nesse caso que estamos usando float, seria o overflow: hidden mesmo..

Depois dá uma olhada nesse vídeo aqui do @MarcoBrunoBR sobre o display inline-block 
https://www.youtube.com/watch?v=Yj9-N9BEVeM

> > Você precisa usar o overflow: hidden;
> > no seu header no css.. o Marco explicou o porque desse comportamento de cortar.. é porque a propriedade float tem o comportamento de tirar do elemento pai.. então no momento que você colocou o float no h1, ele saiu do elemento pai, então o background color ficou apenas para o nav.. o nav subiu porque o float foi pra "frente"..
> 
> o uso de `display: inline-block` não deveria corrigir esse comportamento?

o display: inline-block quando usado ele alinha os elementos e mantém o tamanho padrão deles.. mas nesse caso que estamos usando float, seria o overflow: hidden mesmo..

Depois dá uma olhada nesse vídeo aqui do @MarcoBrunoBR sobre o display inline-block 
https://www.youtube.com/watch?v=Yj9-N9BEVeM

**Comment by icastilhog** [comment]
> > Você precisa usar o overflow: hidden;
> > no seu header no css.. o Marco explicou o porque desse comportamento de cortar.. é porque a propriedade float tem o comportamento de tirar do elemento pai.. então no momento que você colocou o float no h1, ele saiu do elemento pai, então o background color ficou apenas para o nav.. o nav subiu porque o float foi pra "frente"..
> 
> o uso de `display: inline-block` não deveria corrigir esse comportamento?

o display: inline-block quando usado ele alinha os elementos e mantém o tamanho padrão deles.. mas nesse caso que estamos usando float, seria o overflow: hidden mesmo..

Depois dá uma olhada nesse vídeo aqui do @MarcoBrunoBR sobre o display inline-block 
https://www.youtube.com/watch?v=Yj9-N9BEVeM

**Comment by lucaskahl** [comment]
@Morette 

O

> > Você precisa usar o overflow: hidden;
> > no seu header no css.. o Marco explicou o porque desse comportamento de cortar.. é porque a propriedade float tem o comportamento de tirar do elemento pai.. então no momento que você colocou o float no h1, ele saiu do elemento pai, então o background color ficou apenas para o nav.. o nav subiu porque o float foi pra "frente"..
> 
> o uso de `display: inline-block` não deveria corrigir esse comportamento?

Segundo [MZ MDN](https://developer.mozilla.org/pt-BR/docs/Web/CSS/display), display inline-block o elemento gera um bloco com todo o elemento em uma unica linha, na teoria ele faz sim de pegar o maior elemento, porém o elemento filho se sobressai ao elemento pai, e por isso é utilizado o overflow.

https://imgur.com/a/yiqmmd7

Vê essa imagem pra tu entender ^
