### ISSUE TITLE
Erro ao tentar abrir o arquivo .zshrc pelo vim

### ISSUE THREAD

**Issue by leopeli** [CollabCodeTech/forum-do-front-ao-end#48]
Boa noite pessoal.

Quando eu executo no UBUNTU o comando para entrar nas configurações do ZSH através do vim recebo a seguinte mensagem

![image](https://user-images.githubusercontent.com/10725108/49056219-fda22e00-f1e1-11e8-9e1a-bd55eaccf958.png)

E não consigo editar o arquivo para alterar o tema.

**Comment by Pliavi** [comment]
Essa mensagem diz que você tem um arquivo de _swap_ do seu `.zshrc`, é um backup de uma edição anterior feita pelo vim.
Você pode fazer o seguinte:
````sh
mv .zshrc.swp .bkp.zshrc
vim .zshrc
````
Aqui você está trocando o nome do arquivo pra ele não gerar essa mensagem, mas sem perder o arquivo, a partir daí, você pode editar o arquivo `.zshrc`.
Veja se está tudo correto, e confira o conteúdo do _backup_, se estiver tudo certo é só deletar esse `.bkp`

**Comment by FeelipePM** [comment]
@leopeli sua dúvida foi resolvida?

**Comment by leopeli** [comment]
Desculpe.
Sim e não. rsrsrs
Ajudou bastante a entender o que estava pegando. 
Mas quando eu abria o VIM e realizava a alteração não me permitia salvar saindo apenas com o comando:
```:q```
Para conseguir sair e salvar precisei sair com o comando

```:wq```

Agora foi.

Valeu @Pliavi

**Comment by alinefdsouza** [comment]
e como consigo sair dessa tela e abrir o meu terminal pra dar esse comando ai? aqui nao sai disso e nao consigo editar comando sem o terminal limpo

**Comment by Pliavi** [comment]
@alinefdsouza no vim geralmente é o ESC, quando apertar tente digitar o `:q`, deve aparecer escrito lá em baixo, e confirme com o <kbd>enter</kbd>
