### ISSUE TITLE
Duvida sobre position relative.

### ISSUE THREAD

**Issue by sarival** [CollabCodeTech/forum-do-front-ao-end#49]
Fala Galera, Blz?
Estou tentando solucionar o `desafio avançado da aula 003` (centralizar verticalmente o header). Estou tetando solucionar usando position relative para isso (não sei se está certo haha).
Nessas minhas tentativas e pesquisas, vi que podemos usar a propriedade `top` com as unidades de medidas  `px`, `%`, etc...
Porém não estou conseguindo usar a unidade `%` no meu exemplo. Alguém saberia de dizer o por que??

obs: Se eu uso a unidade `px`, o header se distancia do topo da pagina. Com a `%` não.

Segue exemplo do código:

```

header{
    background-color: #e24647;
    color: white;
    margin: 0 115px;
    padding: 55px 60px 95px;
    
    overflow: hidden;
    position: relative;
    top: 50%; 

}

```

**Comment by lucaskahl** [comment]
Top é relativo ao pai, e se você especificar uma porcentagem, é a porcentagem da altura do pai. Mas o pai não tem uma altura (explícita), então isso não funcionará.
Tem várias formas de resolver.. porém.. não vou dar a resposta aqui, é importante você pesquisar, porém vai umas dicas: tu pode utilizar flex-box / position absolute com o pai relative hehe.
Mas se não conseguir, comenta aqui que nós damos um help :)

**Comment by sarival** [comment]
@lucaskahl
Valeu pela resposta. Entendi o motivo de não funcionar a % nesse caso.
Agora vou pesquisar tentar com suas dicas. haha
Valeu mesmo!!!
