### ISSUE TITLE
Dúvida Width position

### ISSUE THREAD

**Issue by GuiiMoraes** [CollabCodeTech/forum-do-front-ao-end#51]
Galera, to num dúvida do seguinte
Na ultima aula o Marco disse que o width, no position absolute, pegava a largura do pai para aplicar a largura do elemento, usei a vi que ele aplica a largura apenas no conteúdo do elemento.
Minha duvida é a seguinte, porque o padding não ta aplicado dos dois lados do elemento, no print que eu tirei, da pra ver a barra de rolagem apenas a direita, mesmo com o computado mostrando padding dos dois lados  

![tela mostrando padding aplicado apenas de um lado com a propriedade width 100% no position absolute](https://user-images.githubusercontent.com/18218319/49115944-41993f80-f283-11e8-9e37-cb4f05114263.JPG)

**Comment by lucaskahl** [comment]
@GuiiMoraes 

Tenta dar um box-sizing: border-box e vê se resolve :)

A propriedade CSS box-sizing é utilizada para alterar a propriedade padrão da box model, usada para calcular larguras (widths) e alturas (heights) dos elementos.

**Comment by GuiiMoraes** [comment]
Cara, tua resposta me ajudou sim, mas acho que tu não entendeu o que eu disse.
Vou tentar explicar aqui o que eu quis dizer e o que entendi sobre isso.
"Na ultima aula o Marco disse que o width, no position absolute, pegava a largura do pai para aplicar a largura do elemento"
Num cenário de width 80%, calcula toda a da largura do pai e deixa a largura do elemento com 80% da largura do pai, ou seja, se o pai tem 100px de largura, o conteúdo do elemento terá 80px.
Minha dúvida era com relação à não estar vendo o padding do lado direito, logo antes do logo, mas isso o Marco explica que ele é pelo posicionamento ficar alinhado da esquerda pra direita.
