### ISSUE TITLE
Commits armazenados em algum cache antes do push?

### ISSUE THREAD

**Issue by Morette** [CollabCodeTech/forum-do-front-ao-end#52]
Olá pessoal, onde ficam armazenados os commits antes de dar push?

Se eu der commit e desligar tudo, quando ligar eu consigo só dar o push? Ele fica armazenado em algum tipo de cache?

**Comment by diegovbarros** [comment]
Fica armazenado no seu git local. Só vai perder se o computador pegar fogo, rs.

**Comment by Pliavi** [comment]
Todas as informações do seu repositório e commits ficam dentro de uma pasta oculta `.git` no seu projeto.
![](https://i.imgur.com/gJvolvm.png)
Então você pode desligar ou levar o projeto pra qualquer lugar (pendrive, cloud, etc) que seus commits estão atrelados à pasta, tu não vai perder nada à menos que essa pasta seja apagada.

**Comment by FeelipePM** [comment]
@Morette  Só comenta pra gente se a sua dúvida foi resolvida =D

**Comment by Morette** [comment]
Valeu pessoal, entendi!



> @Morette Só comenta pra gente se a sua dúvida foi resolvida =D

feito
😉
