### ISSUE TITLE
Alguém sabe informar como sair da tela após o comando git commit --amend?

### ISSUE THREAD

**Issue by washics18** [CollabCodeTech/forum-do-front-ao-end#54]
Editei a frase do meu último commit antes do push mas não consigo salvar e sair da tela.

**Comment by valdemirfilho** [comment]
Tente a sequência de teclas:
`[ESC] q`
ou
`:q! [ENTER]`

**Comment by washics18** [comment]
Quando digito fica assim mas não saiu da tela:
![image](https://user-images.githubusercontent.com/45200025/49172614-5677e080-f320-11e8-9b54-3f8bcc1a51a9.png)

**Comment by MarcoBrunoBR** [comment]
> 
> 
> Quando digito fica assim mas não saiu da tela:
> ![image](https://user-images.githubusercontent.com/45200025/49172614-5677e080-f320-11e8-9b54-3f8bcc1a51a9.png)

Você esta usando o editor de texto chamado nano. Pra sair dele você precisar primeiro teclar CTRL+x, como você fez alteração ele vai te perguntar se você quer salvar as alterações feitas, aí é só você confirmar escrevendo Y e depois apertando o ENTER :-)

Vê se funciona e depois avisa, por favor ;-)

**Comment by washics18** [comment]
Funcionou obrigado.
