### ISSUE TITLE
Aula 004 - O mundo do display - margin/padding ou width/height

### ISSUE THREAD

**Issue by Morette** [CollabCodeTech/forum-do-front-ao-end#58]
Para criar o botão "Comprar" poderia fazer com padding ou margin ao invés da forma como o Marco fez no vídeo?

Ele utilizou width, height, line-height, text-align etc.

**Comment by Pliavi** [comment]
Pode, diria até que deve, na verdade nem entendi muito bem o porque do uso no vídeo, talvez para exemplificar, se sim, talvez não deva ter sido um bom exemplo à se utilizar.

Isso gera alguns problemas:
- Definir `height` te obriga a usar `line-height` pra centralizar;
- Usar o `line-height`, junto ao `border-box` dá esse problema no alinhamento da linha;
  - E usar o caso do `vertical-align` só funciona pra `1px` de borda, valores maiores ficam ainda mais desalinhados (mesmo considerando ele não recomendando usar, apesar de dizer que funciona, é para este único caso)
- Definir uma largura te obriga a alterá-la caso o conteúdo ultrapasse seu tamanho
  - Obs: Porém isso pode ser bom, quando você quer que a largura seja fixa, mas recomendaria usar a largura junto ao padding, tem o mesmo resultado, e usaria apenas onde for necessário

E o esquema com `padding` é bem comum, procure inspecionar botões em sites, até aqui no próprio Github, sempre usam `padding`

**Comment by Morette** [comment]
> Pode, diria até que deve, na verdade nem entendi muito bem o porque do uso no vídeo, talvez para exemplificar, se sim, talvez não deva ter sido um bom exemplo à se utilizar.

Pensei nisso também, que ele queria explicar essa parte.

Valeu, já me esclareceu.
É que no desafio eu havio feito com padding e ficou parecido ao modelo do Zeplin.
