### ISSUE TITLE
Body com altura zerada

### ISSUE THREAD

**Issue by rafael-ff** [CollabCodeTech/forum-do-front-ao-end#59]
Boa noite, pessoal

Estava explorando a opção inspecionar elementos e percebi que ao passar o mouse sobre a tag body este encontra-se com o valor zerado de altura. O que pode ser? O de vcs estão assim?

**Comment by Pliavi** [comment]
É um comportamento esperado, pois você adicionou `position: absolute` no seu `.container` e ele é o único elemento dentro do `body`.

Este comportamento é descrito na MDN:
https://developer.mozilla.org/en-US/docs/Web/CSS/position
(coloquei em inglês porque o português está desatualizado e faltando coisa, principalmente essa parte)

Na sessão [Values](val) em `absolute`, está escrito o seguinte:
> The element is removed from the normal document flow, and no space is created for the element in the page layout. 

Traduzindo:

> O elemento é removido do fluxo normal do documento, e nenhum espaço é criado para o elemento no layout da pagina

O que significa que o elemento com `position: absolute` sai do fluxo comum das tags e não tem tamanho, e como a tag `body` não tem altura definida ela vai de acordo com o tamanho do conteúdo, como seu conteúdo é o `.container` que é `absolute` (logo não tem tamanho), o `body` passa a não ocupar nenhum espaço, tendo altura zerada.


[val]: https://developer.mozilla.org/en-US/docs/Web/CSS/position#Values

**Comment by rafael-ff** [comment]
Obrigado pelo esclarecimento, @Pliavi !!
