### ISSUE TITLE
Aula 005 - border e border-box

### ISSUE THREAD

**Issue by Morette** [CollabCodeTech/forum-do-front-ao-end#62]
Está acontecendo um comportamento estranho quando coloco a propriedade `box-sizing: border-box`

Estou utilizando a propriedade `border: 2px solid #fff`
Porém quando inspeciono o elemento, a borda fica com 1.8

![image](https://user-images.githubusercontent.com/20028647/49328749-a80caf00-f55c-11e8-9d17-84ee8358cfd5.png)

Fiz alguns testes e percebi que não está acompanhando a propriedade `border`. Alguns exemplos:

`border: 1.5px solid #fff`
![image](https://user-images.githubusercontent.com/20028647/49328763-e904c380-f55c-11e8-9582-78096c53a36d.png)

`border: 1.7px solid #fff`
![image](https://user-images.githubusercontent.com/20028647/49328779-1d787f80-f55d-11e8-81c9-e7253c404ab9.png)

`border: 1.9px solid #fff`
![image](https://user-images.githubusercontent.com/20028647/49328802-6c261980-f55d-11e8-920a-7b5e8d4e5337.png)

`border: 2.1px solid #fff`
![image](https://user-images.githubusercontent.com/20028647/49328809-8233da00-f55d-11e8-82a4-9114a1f51b65.png)

Só altera quando coloco `border: 2.4px solid #fff`, mas o comportamento estranho continua para os valores acima
![image](https://user-images.githubusercontent.com/20028647/49328816-aa233d80-f55d-11e8-9b86-c96fe284e01d.png)

**Comment by Pliavi** [comment]
Tem o código aí?
Porque tentei replicar com o que deu pra ver pelas imagens: [Ir para Codepen](https://codepen.io/Pliavi-1472152037/pen/oQmZBW?editors=1100)
Testei tanto no Chrome, Firefox e Firefox Nightly e todos deram 2px de borda.

**Comment by Morette** [comment]
> @Morette , repara se seu navegador está com algum zoom, isso pode dar alterações no valor.
> Se eu não me engano, isso aconteceu com o Marco em alguma aula.

Putz, nunca iria imaginar que era isso...
Valeu!!

@Pliavi obrigado! 
foi o que o @bruno1902 disse.. zoom do navegador.
