### ISSUE TITLE
Prettier está instalado mas não formata quando vou salvar 

### ISSUE THREAD

**Issue by washics18** [CollabCodeTech/forum-do-front-ao-end#65]
Já desinstalei e instalei novamente, quando salvo fica da mesma forma:
![image](https://user-images.githubusercontent.com/45200025/49374906-8db00e00-f6e1-11e8-959c-bdd1697971c8.png)

**Comment by FeelipePM** [comment]
Precisa configurar o JSON do VScode, e colocar:

``` JSON
"editor.formatOnSave": true,
  "prettier.eslintIntegration": true,
```

ai vai funcionar =D

**Comment by FeelipePM** [comment]
te mandei as fotos via telegram.

**Comment by washics18** [comment]
Funcionou valeu !!
