### ISSUE TITLE
Dúvida sobre display: inline-block

### ISSUE THREAD

**Issue by Wanhenri** [CollabCodeTech/forum-do-front-ao-end#68]
Pessoal, na aula004, **"O mundo do display"**, estou reproduzindo de acordo com que o Marco propôs, porém não está dando certo. Vou mandar o print:

[Duvida sobre inline-block](https://github.com/Wanhenri/collab_curso_2018_19/blob/master/aula004/duvidas/Captura%20de%20tela%20de%202018-12-04%2015-13-05.png)

**Comment by mjfneto** [comment]
Oi, @Wanhenri. Fez o link do `botão.css` com o html?

**Comment by Wanderrson** [comment]
<div class="container-store"> abraçando todos os elementos 
		<header class="header-store">
			<h1 class="title-logo"> LOGO </h1>   		
			<nav class="navigation-storre">
				<a class="action" href="#">Produtos</a>
				<a class="action" href="#">Serviços</a>
				<a class="action last" href="#">Carrinho (10)</a>
			</nav>
		</header>
		<div class="button-first">
			<a href="#" class="button-store -second">Adiciona no carrinho
			</a>
			<a href="#" class="button-store ">Comprar</a>
		</div>
	</div>

boa tarde amigo voce tem que colocar um dive abraçando todos os elementos para ficar tudo junto esse e meu codigo

**Comment by Wanderrson** [comment]
boa tarde amigo voce tem que criar uma div para abraçar todos os elementos  e ficar todos em um container so qual quer coisa pode me chamar no telegram

**Comment by Wanderrson** [comment]
![container](https://user-images.githubusercontent.com/44273334/49538478-acb1ca00-f8b2-11e8-9b97-b9807723519f.jpg)

**Comment by FeelipePM** [comment]
> Pessoal, na aula004, **"O mundo do display"**, estou reproduzindo de acordo com que o Marco propôs, porém não está dando certo. Vou mandar o print:
> 
> [Duvida sobre inline-block](https://github.com/Wanhenri/collab_curso_2018_19/blob/master/aula004/duvidas/Captura%20de%20tela%20de%202018-12-04%2015-13-05.png)

Conseguiu resolver?

**Comment by Wanhenri** [comment]
Desculpa a demora pessoal.
Encontrei o problema:

eu tinha colocado esses comando para o body ->
body {
    height: 1200px;
    display: flex;
    flex-direction: column;
    justify-content: center;
   
}

Logo tava restringindo os button em colunas (acredito que seja essa a explicação correta).
Mas a dica de ambos para colocar entre o <div></div> foi excelente!!Tinha esquecido de colocar.

Muito obrigado  @Wanderrson e @FeelipePM pela atenção e prontificação em ajudar.
