### ISSUE TITLE
Templates

### ISSUE THREAD

**Issue by Wanhenri** [CollabCodeTech/forum-do-front-ao-end#69]
Indicaram esse site com vários templates de várias tecnologias. Pode ser util num futuro próximo.

http://echarts.baidu.com/

**Comment by Pliavi** [comment]
Vish, não consegui entender nada do site .-.

**Comment by Wanhenri** [comment]
Onde eu trabalho, uma galera pegou alguns templates desse site e criou algumas soluções interessantes.
Dei print em algumas telas (o conteudo só ta liberado para a intranet).
[link com exemplos](https://github.com/Wanhenri/collab_curso_2018_19/tree/master/trunk)

**Comment by Wanderrson** [comment]
top gostei

**Comment by FeelipePM** [comment]
> Vish, não consegui entender nada do site .-.

lá na sua direita do browser tem como mudar de japones para inglês.
