### ISSUE TITLE
Estou usando o powershell no lugar do hyper mas também não estou tendo sucesso

### ISSUE THREAD

**Issue by washics18** [CollabCodeTech/forum-do-front-ao-end#7]
O PC é Windons 8.1 sou iniciante na área, tentei usar o hyper não consegui e agora estou usando powershell fica dando esse erro:
PS C:\Users\Convidado> cd /mnt/c
cd : Não é possível localizar o caminho 'C:\mnt\c' porque ele não existe.
No linha:1 caractere:1
+ cd /mnt/c
+ ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\mnt\c:String) [Set-Location], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationComm

**Comment by joviane** [comment]
Oi @washics18,

No PowerShell você não precisa entrar no `/mtc`, ele é para o hyper conseguir acessar as pastas do Windows já que ele está rodando em cima de um Ubuntu.

Você pode acessar direto com ` cd C:`

**Comment by lucaskahl** [comment]
Olá @washics18 

Caso não funcione você também pode dar um `cd /d C:`
Deixa um feedback se funcionou ou não :)

**Comment by washics18** [comment]
Tentei agora ficou com esse erro:
PS C:\Users\Convidado> cd/c
cd/c : O termo 'cd/c' não é reconhecido como nome de cmdlet, função, arquivo de script ou programa operável. 
Verifique a grafia do nome ou, se um caminho tiver sido incluído, veja se o caminho está correto e tente novamente.
No linha:1 caractere:1
+ cd/c
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (cd/c:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 

PS C:\Users\Convidado> cd / d c
Set-Location : Não é possível localizar um parâmetro posicional que aceite o argumento 'd'.
No linha:1 caractere:1
+ cd / d c
+ ~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-Location], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.SetLocationCommand

**Comment by GuiiMoraes** [comment]
> Tentei agora ficou com esse erro:
> PS C:\Users\Convidado> cd/c
> cd/c : O termo 'cd/c' não é reconhecido como nome de cmdlet, função, arquivo de script ou programa operável.
> Verifique a grafia do nome ou, se um caminho tiver sido incluído, veja se o caminho está correto e tente novamente.
> No linha:1 caractere:1
> 
> * cd/c
> * ```
>     + CategoryInfo          : ObjectNotFound: (cd/c:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
>   ```
> 
> PS C:\Users\Convidado> cd / d c
> Set-Location : Não é possível localizar um parâmetro posicional que aceite o argumento 'd'.
> No linha:1 caractere:1
> 
> * cd / d c
> * ```
>     + CategoryInfo          : InvalidArgument: (:) [Set-Location], ParameterBindingException
>     + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.SetLocationCommand
>   ```

Fala, @washics18 
Tive um problema parecido, tenta os seguintes passos

1. Navega até a raiz do seu diretório usando "..", a linha de comando fica assim
`PS C:\Users\Convidado cd ..` 

2. Tu vai usar até chegar no C:
`PS C:\Users\Convidado cd ..` 
`PS C:\Users cd ..`
`PS C:\ cd ..` 

Fica assim
```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\Users\guiim> cd ..
PS C:\Users> cd ..
PS C:\>
```

**Comment by lucaskahl** [comment]
Olá @washics18,

Ao contrário do cmd, no powershell você teria que utilizar o seguinte comando **(Caso queira ir para o Disco D)**

`
PS C:\Users\lucas> set-location -path D:
PS D:\>

` 

Caso você queria ir pra **pasta RAIZ** do teu disco local C, tu pode utilizar o exemplo acima de utilizar

`
cd ..
`

Caso tu for utilizar o cmd tu pode utilizar o exemplo que eu dei acima

`
cd /d C:
`

**Comment by joviane** [comment]
@washics18 você está colocando o comando junto com a barra ou com espaço indevido. Ao invés de `cd/c` ou `cd / d c` tenta como o @GuiiMoraes falou ou com `cd  c:` ou `cd  /d  c:`
Não pode esquecer dos dois pontos no comando também.

**Comment by krivax** [comment]
só coloca exemplo cd d: ou cd c:

**Comment by washics18** [comment]
Fiz até chegar a raiz deu certo. Aí quando coloquei mkdir do-front-ao-end dar um erro:
PS C:\> mkdir do-front-ao-end
mkdir : O acesso ao caminho 'do-front-ao-end' foi negado.
No linha:1 caractere:1
+ mkdir do-front-ao-end
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (C:\do-front-ao-end:String) [New-Item], UnauthorizedAccessException
    + FullyQualifiedErrorId : CreateDirectoryUnauthorizedAccessError,Microsoft.PowerShell.Commands.NewItemCommand

Estou quase lá vocês sabem se tenho que inserir mais alguma coisa?

**Comment by krivax** [comment]
Se n me engano seu Windows está com proteção. Tem que executar o powershell em modo administrador

**Comment by FeelipePM** [comment]
Como o @krivax disse você está usando o user/convidado tente usar seu user/washics18 que é o administrador da máquina, poderia ser isso o problema.

**Comment by ozeaseromina** [comment]
Bom dia!
Alguém pode me ajudar estou tentando gerar a chave ssh publica e dá esse erro 
C:\WINDOWS\system32>cd /C:/Users/ozeaseromina/ .ssh/
A sintaxe do nome do arquivo, do nome do diretório ou do rótulo do volume está incorreta.

C:\WINDOWS\system32>cd /C:/Users/ozeaserominaC:\Users\romin/.ssh/id_ed25519
A sintaxe do nome do arquivo, do nome do diretório ou do rótulo do volume está incorreta.

C:\WINDOWS\system32> cd /C:\Users\romin/.ssh/id_ed25519.pub
A sintaxe do nome do arquivo, do nome do diretório ou do rótulo do volume está incorreta.

C:\WINDOWS\system32>C:\Users\romin/.ssh/id_ed25519.pub

C:\WINDOWS\system32>ls
'ls' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.

C:\WINDOWS\system32>ls
'ls' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.

C:\WINDOWS\system32>cat id_ed25519.pub
'cat' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.

**Comment by ozeaseromina** [comment]
Tentei solucionar o erro com os comandos sugeridos acima, mas não consegui, sou iniciante e estou com dificuldade, se poderem me ajudar, por gentileza.

**Comment by ozeaseromina** [comment]
Eu consigo criar a chave ssh, porém no momento que coloco o comando ls não aparece as minhas chaves pub. e nem a privada, não consigo sair desse estágio.

**Comment by brunobolting** [comment]
Olá @ozeaseromina, tudo bem?

Acho que o que está acontecendo é apenas uma confusão nos comandos, dependendo de como você está usando o terminal do Windows os comandos vão ser diferentes do UNIX/Linux. Tenta com esses outros comandos:

Para listar o conteúdo de uma pasta use o comando `dir`. 
Pra listar o conteúdo de um arquivo, se não estou enganado, use o comando `type`. Ex: `type id_ed25519.pub`

Outra coisa é que você está tentando entrar diretamente no arquivo, e isso não é possível, ex:
```
❌
cd /C:\Users\romin/.ssh/id_ed25519.pub
```
O certo é entrarmos na pasta, pra depois acessarmos o arquivo:
```
✅
cd /C:\Users\romin/.ssh/
type id_ed25519.pub
```

Se você conseguir usar o terminal PowerShell ele vai funcionar melhor que o Command, tem alguns comandos mais parecidos com o Unix, acho que vai facilitar sua vida.
Outra coisa, não validei se os diretórios estão corretos, apenas peguei como exemplo os que você forneceu, tente usar a tecla Tab do teclado para autocompletar os diretórios, assim fica mais fácil saber se estamos indo pro caminho certo.

Caso ainda não consiga prosseguir, mande mensagem novamente para analisarmos mais a fundo seu problema.

Abraço!

**Comment by ozeaseromina** [comment]
Não consegui ainda estou entrando pelo Git Bash, agora deu esse erro  
Default  Public  Todos\ os\ Usuários  Usuário\ Padrão  desktop.ini  romin

**Comment by brunobolting** [comment]
Oi @ozeaseromina, só com esse erro fica difícil dizer, conseguiria gravar um vídeo ou algo assim?

Da uma olhada se consegue seguir esse tutorial aqui:
https://confluence.atlassian.com/bitbucketserver/creating-ssh-keys-776639788.html#CreatingSSHkeys-CreatinganSSHkeyonWindows
