### ISSUE TITLE
Hyper doidão

### ISSUE THREAD

**Issue by MarciaCogitare** [CollabCodeTech/forum-do-front-ao-end#70]
Uso Ubuntu 18.04, o Hyper não quer colaborar. Ele some o que tá escrito dentro e fica só a caixa preta e tudo travando. Quando abro dá o seguinte erro. Oia a fotita ae : (
![captura de tela de 2018-12-04 23-46-06](https://user-images.githubusercontent.com/24261289/49485961-f1daeb00-f823-11e8-8856-c1e376e30925.png)

**Comment by Pliavi** [comment]
Se pá devem ter esquecido essa dependência no .deb do Hyper, isso deve resolver:
`sudo apt install libgconf2-4`

**Comment by MarciaCogitare** [comment]
@Pliavi Obrigada, vou testar e te falo que deu certo : )

**Comment by MarciaCogitare** [comment]
@Pliavi Deu certo, sumiu a mensagem chata : ) Valew
