### ISSUE TITLE
HELP - Github não link a origin - master com xxx em vermelho

### ISSUE THREAD

**Issue by MarciaCogitare** [CollabCodeTech/forum-do-front-ao-end#72]
![duvida github](https://user-images.githubusercontent.com/24261289/49551045-db409c80-f8d4-11e8-8b06-e8b35325e9e9.png)

**Comment by divetta** [comment]
@MarciaCogitare pelo log parece que o seu branch master local está atrás (behind) do branch remoto. Ele sugere que você execute o comando `git pull` para baixar as alterações presentes no repositório remoto para a sua branch local.

Tente executar o `git pull` e depois o `git push`.

**Comment by MarciaCogitare** [comment]
> @MarciaCogitare pelo log parece que o seu branch master local está atrás (behind) do branch remoto. Ele sugere que você execute o comando `git pull` para baixar as alterações presentes no repositório remoto para a sua branch local.
> 
> Tente executar o `git pull` e depois o `git push`.

@divetta fiz isso e continua esquisito
![master red](https://user-images.githubusercontent.com/24261289/49556553-77759e00-f8eb-11e8-8a0c-95987989aea4.png)
