### ISSUE TITLE
Quando vou fazer o espaçamento da LOGO com o title Fone top,feliz e caro a linha do LOGO sobe como ficasse fora do layout

### ISSUE THREAD

**Issue by washics18** [CollabCodeTech/forum-do-front-ao-end#74]
No desafio 5 assistir a aula explicando o espaçamento mas quando realizo a linha da logo fica ultrapassando a tela. No caso da figura no zeplin o espaçamento é 138px quando coloco header-store sobe demais como estivesse saindo da tela.
.header-store {
  color: #fff;
  overflow: hidden;
  margin-bottom: 138px;

![image](https://user-images.githubusercontent.com/45200025/49649611-6bcbc980-fa08-11e8-8f1d-f3d232c6b483.png)

**Comment by FeelipePM** [comment]
É normal acontecer isso por conta do tamanho da tela que você está usando, se jogar o layout em uma tv vai funcionar tranquilamente, e que não está totalmente responsivo ainda. acho que vamos ter uma aula de responsivo para deixar esse layout mais funcional. uma alternativa para você é diminuir o zoom do browser

**Comment by washics18** [comment]
Eu coloquei px menor ajustar
