### ISSUE TITLE
Texto "Busca" não aplica a cor branca. Alguém para um help?

### ISSUE THREAD

**Issue by PabloFerreiraB** [CollabCodeTech/forum-do-front-ao-end#75]
### Dúvida - Aula 007 (Layout da busca, simples e feliz).

- Vi mais de uma vez a aula e não encontrei o motivo de porque o meu texto BUSCA não aplica o color herdado ou até mesmo passando o valor direto.
- Todas as outras propriedades aplica corretamente pra ele.

**Comment by luxu** [comment]
Aconteceu cmg isso, mas num sei pq era só no Chrome, abri no FF e foi feliz!

**Comment by Pliavi** [comment]
É que a propriedade `color` no _input_ tem sua função focada no texto digitado pelo usuário, o Firefox tem essa peculiaridade de ter essa "herança seletiva" e acabar pegando a cor no _placeholder_ também.

Pra fazer com que o texto do _placeholder_ fique branco nos demais navegadores, e recomendado para o Firefox também, pois permite usar propriedades diferentes para cada, você deve utilizar o **pseudo elemento** `::placeholder` no input.
````css
/* peguei o seletor do seu repo */
.header-store [type="search"]::placeholder {
    color: #fff;
}
````

**Comment by PabloFerreiraB** [comment]
Obrigado @Pliavi , era isso mesmo.
Estou fechando essa issue com a conclusão.
