### ISSUE TITLE
Dúvida Aula 010 - Header Responsivo

### ISSUE THREAD

**Issue by KlausSantos** [CollabCodeTech/forum-do-front-ao-end#79]
`Marcão e galera, acompanhando a aula fui efetuando as modificações, mas pelo fato de está no notebook e a minha tela ser muito menor que a do monitor da aula, as medidas não ficaram legais.`
### minha dúvida é: ###
- Para resolver isto, o mais indicado é usar a unidade de medida em porcetagem ao invés de pixel?
#### outra dúvida ####
- Na aula foram feitos vários `@media` de vários tamanhos. Existe um padrão de quantos fazer, ou a cada quebra de layout se faz um?

**Comment by lucaskahl** [comment]
Opa, @KlausSantos Klaus, tudo bem ?

Creio que o @MarcoBrunoBR utilizou breakpoints de acordo com a tela dele, normalmente em breakpoints você utiliza px/em e não % ( pois é mais fácil tu quebrar em um pixel certo invez de pegar a % da tela do usuário e fazer a quebra ( minha opinião ) ).

A quantidade de breakpoints que vc vai precisar usar, é o que determina a qualidade do layout, quando melhor ele for pensando, menos breakpoints vc vai usar, se vc precisar usar tanta coisa assim provavelmente o erro estava no design do layout que não era responsivo (ou não era responsivo corretamente). Normalmente você da suporte até o tamanho decidido pelo designer/cliente

Na aula, como mencionei, o marco utilizou breakpoints de acordo com a quebra dos elementos, tu pode fazer assim também ou colocando um breakpoint fixo.

Segue um exemplo de breakpoint fixo:

phone-only 
    @media (max-width: 599px)
 tablet-portrait-up 
    @media (min-width: 600px)
 ablet-landscape-up 
    @media (min-width: 900px) 
desktop-up 
    @media (min-width: 1200px)
big-desktop-up 
    @media (min-width: 1800px)

**Comment by PabloFerreiraB** [comment]
E ai @KlausSantos tranquilo, aconselho você assistir essa Live de mentoria que ele tirou várias dúvidas, inclusive essas suas.

Segue o link: https://www.youtube.com/watch?v=7B0CIoFzbwQ

**Comment by KlausSantos** [comment]
@PabloFerreiraB vou ver sim, obrigado.
@lucaskahl entendi, mas se eu usar os breakpoints de acordo com minha tela, funcionará nas diferentes telas dos demais usuários?
