### ISSUE TITLE
ZSH ja habilitado ao abrir o Hyper

### ISSUE THREAD

**Issue by CristianoMorgante** [CollabCodeTech/forum-do-front-ao-end#8]
Galera, da pra configurar o hyper para quando ao abrir o mesmo ja executar o zsh automaticamente? 
Outra coisa, o meu não reconhece o sudo, é normal?

**Comment by Rod94** [comment]
voce instalou o ubuntu como está no link ?

**Comment by CristianoMorgante** [comment]
> 
> 
> voce instalou o ubuntu como está no link ?

Sim.

**Comment by CristianoMorgante** [comment]
Consegui!!
Editei o `nano ~/ .bashrc`  acrescentei  `chsh -s /usr/bin/zsh`  , na primeira linha do documento. 
E tinha um "Whrited by MarcoBrunoBR" no inicio da config do hyper, apaguei agora deu certo.
;-)
