### ISSUE TITLE
Configuração do VSCode

### ISSUE THREAD

**Issue by tjcm** [CollabCodeTech/forum-do-front-ao-end#83]
Tô bem atrasado no curso, mas botando em dia as coisas. Só que fiquei com uma dúvida sobre a configuração do VSCode.

Sempre que alguém fala pra abrir o json de configuração do VSCode, manda ir em "Configurações" e os 3 pontinhos. Mas no meu VSCode não tem 3 pontinhos específicos pra configuração, só os que sempre ficam ali em cima. Não estou conseguindo acessar o json de jeito nenhum.

Olha como aparece pra mim:

![image](https://user-images.githubusercontent.com/37338357/49965140-1ce7cd80-fefb-11e8-82a2-fbff0952c672.png)

Quando clico naqueles 3 pontinhos ali a direita não tem opção de abrir json

![image](https://user-images.githubusercontent.com/37338357/49965231-5f110f00-fefb-11e8-9351-cf32ae298606.png)

Alguém sabe oq to fazendo de errado?

**Comment by tjcm** [comment]
Tudo isso pra tentar fazer o prettier funcionar pra formatar on save, mas infelizmente não funciona. :(

**Comment by Pliavi** [comment]
Estranho, realmente deveria ter os 3 pontinhos logo abaixo desses que você tá vendo.

Na dúvida, veja se seu VSCode está atualizado e utilize pelo seguinte:
- Aperte CTRL+SHIFT+P pra abrir a busca de opções
- Digite: "Settings(JSON)" enquanto tu digita já deverá aparecer.
- Enter

Talvez não seja a melhor forma, mas deve resolver por hora.

**Comment by tjcm** [comment]
Tá atualizado na última versão sim. 

Fazendo essa busca manual eu consegui acessar o json! Mas ainda acho estranho que pra todo mundo aparece os pontinhos e não pra mim. Obrigado pela ajuda!

**Comment by EudesJS** [comment]
E apertando CTRL + , não aparecem os 3 pontinhos?

**Comment by Rod94** [comment]
Nessa parte das Settings, se você clicar nas chaves que estão próximas dos 3 pontinhos, ele abre o settings.json

**Comment by tjcm** [comment]
> 
> 
> Nessa parte das Settings, se você clicar nas chaves que estão próximas dos 3 pontinhos, ele abre o settings.json

Funcionou!!!! Muito obrigado
