### ISSUE TITLE
Problema com desafio básico - coração se movendo com o hover.

### ISSUE THREAD

**Issue by sarival** [CollabCodeTech/forum-do-front-ao-end#85]
Boa tarde!
Alguém sabe me dizer o porque ao usar o "hover" no coração (desafio básico) ele acaba se deslocando?

**Comment by EudesJS** [comment]
Vi algumas formas de resolver com box-sizing:border-box, pois pelo que li é algo relacionado à margin, padding dos elementos ao redor, outra forma utilizava o calc...enfim, deixei resolvido apenas apagando o transform: translateX e Y. Veja se desta forma resolve pra vc @sarival

**Comment by Morette** [comment]
Você está aplicando o hover no elemento pai dele e não no elemento em si

você precisa usar assim: 
```
<div class=classe-pai>
   <img src=# class="heart/>
</div>
```

```
.classe-pai > .heart:hover {
   transform: scale(2);
}
```

veja se não está usando o hover na `classe-pai`
aconteceu isso comigo ontem

**Comment by sarival** [comment]
@EudesJS @Morette Valeu pela Ajuda.

Realmente estava realizando o 'transform' na classe pai. Agora coloquei direto na classe "img" e resolveu.

Valeu mais uma vez! 
Abraços
