### ISSUE TITLE
#Aula 011 - Dúvida @max-width

### ISSUE THREAD

**Issue by KlausSantos** [CollabCodeTech/forum-do-front-ao-end#88]
Porque na tela do meu notebook não tá respeitando o max-width 1310px, a tela está no tamanho de 1305 e não funciona - [imagem01](https://uploaddeimagens.com.br/imagens/captura_de_tela_de_2018-12-16_22-16-27-png), mas quando chega em 1297 aí fica com o comportamento esperado - [imagem02](https://uploaddeimagens.com.br/imagens/captura_de_tela_de_2018-12-16_22-17-09-png) ?.

**Comment by MarcoBrunoBR** [comment]
Vixi! Essa eu não sei @KlausSantos. Por favor, me chama no telegram pra marcamos uma call e ver se consigo te ajudar.

**Comment by Morette** [comment]
@KlausSantos tenta ver se não está com zoom.
Quando apliquei zoom no meu o comportamente era diferente, aí passei a utilizar zoom sempre em 100%, mesmo quando ficasse ruim de ver a página toda.
