### ISSUE TITLE
Aula 010 - Header Responsivo - Versão mobile não fica responsivo

### ISSUE THREAD

**Issue by Morette** [CollabCodeTech/forum-do-front-ao-end#91]
Na parte do vídeo em que o Marco muda para ver se cabe na tela do Iphone 6 e percebi que aqui no meu ele não ficou responsivo, apenas reduziu o zoom da tela.

![image](https://user-images.githubusercontent.com/20028647/50122217-9f95c300-0242-11e9-893e-9ae4e2daea49.png)

Na versão desktop está ok.

![image](https://user-images.githubusercontent.com/20028647/50122251-b89e7400-0242-11e9-9010-b72bb7539c66.png)

**Comment by EudesJS** [comment]
Bom dia @Morette .  A pagina do responsivo pode não estar atualizando corretamente, como aconteceu comigo. Indico verificar novamente pois a página se comporta normal quando diminui com a versão Desktop, então está correto. Bons estudos.

**Comment by Morette** [comment]
> A pagina do responsivo pode não estar atualizando corretamente, como aconteceu comigo.

Eu pensei nisso. Fechei a página, abri um novo live server e até abrindo o arquivo html e continuou a mesma coisa. Minha dúvida é como resolver. 😞

**Comment by EudesJS** [comment]
Vc já subiu estes códigos? Posso ajudar, mas somente vendo o que está acontecendo.

**Comment by EudesJS** [comment]
Verifique tb se esta meta está dentro do teu head;
```html
<meta name="viewport" content="width=device-width, initial-scale=1">

**Comment by Morette** [comment]
Opa, subi sim.
[Repositório](https://github.com/Morette/do-front-ao-end/tree/master/loja-fone)

**Comment by EudesJS** [comment]
É a tag meta mesmo

**Comment by Morette** [comment]
Valeu!
Resolveu aqui.

**Comment by Wanhenri** [comment]
@EudesJS  Qual seria a finalidade da tag meta  **<meta name="viewport" content="width=device-width, initial-scale=1">**  ??
Estou finalizando hoje a aula 10 e vi essa dúvida.
No meu não deu esse problema; é mais para uma questão de aprendizado mesmo.
Muito obrigado.

**Comment by EudesJS** [comment]
Opa Wanderson, tudo bem? A tag meta viewport indica ao browser como controlar as dimensões e escala da página em dispositivos com telas menores. Sem esta instrução a página apenas diminui o zoom para adaptar o conteúdo. A parte do content....device=device-width estipula que a largura da tela siga a largura da tela do dispositivo utilizado.  Initial-scale=1.0 indica a escala de zoom inicial quando a tela for carregada....esta parte do scale é necessária devido à diferença entre pixels lógicos e físicos.
Verifique novamente se tudo funciona corretamente ao redimensionar, pois como estamos trabalhando com conteúdo responsivo esta tag é indispensável.

**Comment by Wanhenri** [comment]
Interessante essas informações.

Muito obrigado pelo esclarecimento.
