### ISSUE TITLE
Dúvida sobre o header na aula 006

### ISSUE THREAD

**Issue by rodrigofelix12** [CollabCodeTech/forum-do-front-ao-end#92]
Boa noite.
Segui o código apresentado na aula 006, porém no final meu header continua sem aparecer.
Alguém pode me ajudar?

**Comment by EudesJS** [comment]
Bom dia @rodrigofelix12 . Este problema é corrigido na aula 8 se não me engano, na parte a qual o Marco introduz sobre responsivo. Fica tranquilo. Algumas situações ele deixa rolar de propósito, mas nada fica sem resolução. Bons estudos.

**Comment by rodrigofelix12** [comment]
Bom dia @EudesJS, valeu por responder, já tava ficando nervoso por não entender o que estava acontecendo rsrsrs. Vou seguir as aulas normalmente pra ver como solucionar.
Obrigado.
